site_name: XZMJX
site_url: https://yzmjy.github.io
theme:
  name: material

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - CEPH
        - 刷题
        - CPP
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
      blog_toc: true
nav:
  - Home: index.md
  - Blog:
      - blog/index.md