site_name: XZMJX
site_url: https://yzmjy.github.io

# Repository
repo_name: YzmjY/YzmjY.github.io
repo_url: https://github.com/YzmjY/YzmjY.github.io

theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/link
    #     name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  icon:
    annotation: material/eye-circle
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
        - zh
  - blog:
      archive_date_format: yyyy
      categories_allowed:
        - CEPH
        - CPP
        - Hot150
        - Minio
        - K8S
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
      blog_toc: true
  - minify:
      minify_html: true
  - tags

hooks:
  - overrides/hooks/shortcodes.py
  - overrides/hooks/translations.py
  
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
      - Tags: blog/tags.md
  - CEPH文档翻译:
    - ceph_doc/index.md
    - CEPH文件系统:
      - ceph_doc/ceph_file_system/index.md
      - "CephFS 概念":
        - ceph_doc/ceph_file_system/cephfs_concepts/mds-states.md 
        - ceph_doc/ceph_file_system/cephfs_concepts/posix.md 
        - ceph_doc/ceph_file_system/cephfs_concepts/mds-journaling.md 
        - ceph_doc/ceph_file_system/cephfs_concepts/file-layouts.md 
        - ceph_doc/ceph_file_system/cephfs_concepts/mdcache.md
        - ceph_doc/ceph_file_system/cephfs_concepts/dynamic-metadata-mangement.md
        - ceph_doc/ceph_file_system/cephfs_concepts/cephfs-io-path.md
        - ceph_doc/ceph_file_system/cephfs_concepts/charmap.md
        - ceph_doc/ceph_file_system/cephfs_concepts/lazyio.md
        - ceph_doc/ceph_file_system/cephfs_concepts/dirfrags.md
        - ceph_doc/ceph_file_system/cephfs_concepts/multimds.md
        - ceph_doc/ceph_file_system/cephfs_concepts/snapshots.md
      - "开发者指南":
        - ceph_doc/ceph_file_system/developer-guides/capabilities.md
        - ceph_doc/ceph_file_system/developer-guides/journaler.md

    - CEPH架构: ceph_doc/architecture/architecture.md 
  - 数据结构与算法: 
    - lc/index.md
    - 数据结构与算法:
      - lc/algo/index.md
      - "基础知识":
        - lc/algo/array.md
        - lc/algo/string.md
    - 刷题:
      - lc/top-interview-150/index.md
      - "top150":
        - "数组/字符串":
          - lc/top-interview-150/1_88_合并两个有序数组.md
          - lc/top-interview-150/2_27_移除元素.md
          - lc/top-interview-150/3_26_删除有序数组中的重复项.md
          - lc/top-interview-150/4_80_删除有序数组中的重复项 II.md
          - lc/top-interview-150/5_169_多数元素.md
          - lc/top-interview-150/6_189_轮转数组.md
          - lc/top-interview-150/7_121_买卖股票的最佳时机.md
          - lc/top-interview-150/8_122_买卖股票的最佳时机 II.md
          - lc/top-interview-150/9_55_跳跃游戏.md
          - lc/top-interview-150/10_45_跳跃游戏 II.md
          - lc/top-interview-150/11_274_H 指数.md
          - lc/top-interview-150/12_380_O(1)时间插入、删除和获取随机元素.md
          - lc/top-interview-150/13_238_除自身以外数组的乘积.md
          - lc/top-interview-150/14_134_加油站.md
          - lc/top-interview-150/15_135_分发糖果.md
          - lc/top-interview-150/16_42_接雨水.md
          - lc/top-interview-150/17_13_罗马数字转整数.md
          - lc/top-interview-150/18_12_整数转罗马数字.md
          - lc/top-interview-150/19_58_最后一个单词的长度.md
          - lc/top-interview-150/20_14_最长公共前缀.md
          - lc/top-interview-150/21_ 151_反转字符串中的单词.md
          - lc/top-interview-150/22_6_Z字形变换.md
          - lc/top-interview-150/23_28_找出字符串中第一个匹配项的下标.md
          - lc/top-interview-150/24_68_文本左右对齐.md
        - "双指针":
          - lc/top-interview-150/25_125_验证回文串.md
          - lc/top-interview-150/26_392_判断子序列.md
          - lc/top-interview-150/27_167_两数之和II-输入有序数组.md
          - lc/top-interview-150/28_11_盛最多水的容器.md
          - lc/top-interview-150/29_15_三数之和.md
        - "滑动窗口":
          - lc/top-interview-150/30_209_长度最小的子数组.md
          - lc/top-interview-150/31_3_无重复字符的最长子串.md
          - lc/top-interview-150/32_30_串联所有单词的子串.md
          - lc/top-interview-150/33_76_最小覆盖子串.md
        - "矩阵":
          - lc/top-interview-150/34_36_有效的数独.md
          
